apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: bookstore
  APP_ENV: development
  LOG_LEVEL: info